//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package it.equitalia.gestorefascicolows.source;

import javax.xml.ws.WebFault;

@WebFault(name = "Fault", targetNamespace = "http://srv.gestorefascicolows.equitalia.it")
public class FaultType
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private it.equitalia.gestorefascicolows.srv.FaultType faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public FaultType(String message, it.equitalia.gestorefascicolows.srv.FaultType faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param message
     * @param cause
     */
    public FaultType(String message, it.equitalia.gestorefascicolows.srv.FaultType faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.equitalia.gestorefascicolows.srv.FaultType
     */
    public it.equitalia.gestorefascicolows.srv.FaultType getFaultInfo() {
        return faultInfo;
    }

}
