//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//


package it.equitalia.gestorefascicolows.dati;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the it.equitalia.gestorefascicolows.dati package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EntityItemRenderingType_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "renderingType");
    private final static QName _EntityItemEntityItemRef_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "entityItemRef");
    private final static QName _EntityItemEntityDescr_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "entityDescr");
    private final static QName _DataValueValue_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "value");
    private final static QName _DataValueValueCssClass_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "valueCssClass");
    private final static QName _DataValueTitleCssClass_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "titleCssClass");
    private final static QName _DataValueDataTypeDescr_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "dataTypeDescr");
    private final static QName _GetCartellaWSResponseFascicolo_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "fascicolo");
    private final static QName _AnagraficaRagioneSociale_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "ragioneSociale");
    private final static QName _AnagraficaCognome_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "cognome");
    private final static QName _AnagraficaNome_QNAME = new QName("http://dati.gestorefascicolows.equitalia.it", "nome");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: it.equitalia.gestorefascicolows.dati
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InsertTelefonoWSResponse }
     * 
     */
    public InsertTelefonoWSResponse createInsertTelefonoWSResponse() {
        return new InsertTelefonoWSResponse();
    }

    /**
     * Create an instance of {@link SearchFascicoloWSRequest }
     * 
     */
    public SearchFascicoloWSRequest createSearchFascicoloWSRequest() {
        return new SearchFascicoloWSRequest();
    }

    /**
     * Create an instance of {@link DeleteTelefonoWSResponse }
     * 
     */
    public DeleteTelefonoWSResponse createDeleteTelefonoWSResponse() {
        return new DeleteTelefonoWSResponse();
    }

    /**
     * Create an instance of {@link DataValue }
     * 
     */
    public DataValue createDataValue() {
        return new DataValue();
    }

    /**
     * Create an instance of {@link AperturaFascicoloWSResponse }
     * 
     */
    public AperturaFascicoloWSResponse createAperturaFascicoloWSResponse() {
        return new AperturaFascicoloWSResponse();
    }

    /**
     * Create an instance of {@link DeleteEmailWSResponse }
     * 
     */
    public DeleteEmailWSResponse createDeleteEmailWSResponse() {
        return new DeleteEmailWSResponse();
    }

    /**
     * Create an instance of {@link InsertTelefonoWSRequest }
     * 
     */
    public InsertTelefonoWSRequest createInsertTelefonoWSRequest() {
        return new InsertTelefonoWSRequest();
    }

    /**
     * Create an instance of {@link GetCartellaWSResponse }
     * 
     */
    public GetCartellaWSResponse createGetCartellaWSResponse() {
        return new GetCartellaWSResponse();
    }

    /**
     * Create an instance of {@link SearchFascicoloWSResponse }
     * 
     */
    public SearchFascicoloWSResponse createSearchFascicoloWSResponse() {
        return new SearchFascicoloWSResponse();
    }

    /**
     * Create an instance of {@link GetFascicoloWSResponse }
     * 
     */
    public GetFascicoloWSResponse createGetFascicoloWSResponse() {
        return new GetFascicoloWSResponse();
    }

    /**
     * Create an instance of {@link DeleteIndirizzoWSRequest }
     * 
     */
    public DeleteIndirizzoWSRequest createDeleteIndirizzoWSRequest() {
        return new DeleteIndirizzoWSRequest();
    }

    /**
     * Create an instance of {@link InsertEmailWSResponse }
     * 
     */
    public InsertEmailWSResponse createInsertEmailWSResponse() {
        return new InsertEmailWSResponse();
    }

    /**
     * Create an instance of {@link Indirizzo }
     * 
     */
    public Indirizzo createIndirizzo() {
        return new Indirizzo();
    }

    /**
     * Create an instance of {@link FascicoloList }
     * 
     */
    public FascicoloList createFascicoloList() {
        return new FascicoloList();
    }

    /**
     * Create an instance of {@link Fascicolo }
     * 
     */
    public Fascicolo createFascicolo() {
        return new Fascicolo();
    }

    /**
     * Create an instance of {@link ChiusuraFascicoloWSResponse }
     * 
     */
    public ChiusuraFascicoloWSResponse createChiusuraFascicoloWSResponse() {
        return new ChiusuraFascicoloWSResponse();
    }

    /**
     * Create an instance of {@link GetFascicoloWSRequest }
     * 
     */
    public GetFascicoloWSRequest createGetFascicoloWSRequest() {
        return new GetFascicoloWSRequest();
    }

    /**
     * Create an instance of {@link Anagrafica }
     * 
     */
    public Anagrafica createAnagrafica() {
        return new Anagrafica();
    }

    /**
     * Create an instance of {@link EntityItem }
     * 
     */
    public EntityItem createEntityItem() {
        return new EntityItem();
    }

    /**
     * Create an instance of {@link DeleteIndirizzoWSResponse }
     * 
     */
    public DeleteIndirizzoWSResponse createDeleteIndirizzoWSResponse() {
        return new DeleteIndirizzoWSResponse();
    }

    /**
     * Create an instance of {@link GetCartellaWSRequest }
     * 
     */
    public GetCartellaWSRequest createGetCartellaWSRequest() {
        return new GetCartellaWSRequest();
    }

    /**
     * Create an instance of {@link InsertIndirizzoWSResponse }
     * 
     */
    public InsertIndirizzoWSResponse createInsertIndirizzoWSResponse() {
        return new InsertIndirizzoWSResponse();
    }

    /**
     * Create an instance of {@link DeleteTelefonoWSRequest }
     * 
     */
    public DeleteTelefonoWSRequest createDeleteTelefonoWSRequest() {
        return new DeleteTelefonoWSRequest();
    }

    /**
     * Create an instance of {@link ChiusuraFascicoloWSRequest }
     * 
     */
    public ChiusuraFascicoloWSRequest createChiusuraFascicoloWSRequest() {
        return new ChiusuraFascicoloWSRequest();
    }

    /**
     * Create an instance of {@link InsertIndirizzoWSRequest }
     * 
     */
    public InsertIndirizzoWSRequest createInsertIndirizzoWSRequest() {
        return new InsertIndirizzoWSRequest();
    }

    /**
     * Create an instance of {@link EMail }
     * 
     */
    public EMail createEMail() {
        return new EMail();
    }

    /**
     * Create an instance of {@link InsertEmailWSRequest }
     * 
     */
    public InsertEmailWSRequest createInsertEmailWSRequest() {
        return new InsertEmailWSRequest();
    }

    /**
     * Create an instance of {@link DeleteEmailWSRequest }
     * 
     */
    public DeleteEmailWSRequest createDeleteEmailWSRequest() {
        return new DeleteEmailWSRequest();
    }

    /**
     * Create an instance of {@link Telefono }
     * 
     */
    public Telefono createTelefono() {
        return new Telefono();
    }

    /**
     * Create an instance of {@link AperturaFascicoloWSRequest }
     * 
     */
    public AperturaFascicoloWSRequest createAperturaFascicoloWSRequest() {
        return new AperturaFascicoloWSRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "renderingType", scope = EntityItem.class)
    public JAXBElement<String> createEntityItemRenderingType(String value) {
        return new JAXBElement<String>(_EntityItemRenderingType_QNAME, String.class, EntityItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "entityItemRef", scope = EntityItem.class)
    public JAXBElement<String> createEntityItemEntityItemRef(String value) {
        return new JAXBElement<String>(_EntityItemEntityItemRef_QNAME, String.class, EntityItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "entityDescr", scope = EntityItem.class)
    public JAXBElement<String> createEntityItemEntityDescr(String value) {
        return new JAXBElement<String>(_EntityItemEntityDescr_QNAME, String.class, EntityItem.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "value", scope = DataValue.class)
    public JAXBElement<String> createDataValueValue(String value) {
        return new JAXBElement<String>(_DataValueValue_QNAME, String.class, DataValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "valueCssClass", scope = DataValue.class)
    public JAXBElement<String> createDataValueValueCssClass(String value) {
        return new JAXBElement<String>(_DataValueValueCssClass_QNAME, String.class, DataValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "renderingType", scope = DataValue.class)
    public JAXBElement<String> createDataValueRenderingType(String value) {
        return new JAXBElement<String>(_EntityItemRenderingType_QNAME, String.class, DataValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "titleCssClass", scope = DataValue.class)
    public JAXBElement<String> createDataValueTitleCssClass(String value) {
        return new JAXBElement<String>(_DataValueTitleCssClass_QNAME, String.class, DataValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "dataTypeDescr", scope = DataValue.class)
    public JAXBElement<String> createDataValueDataTypeDescr(String value) {
        return new JAXBElement<String>(_DataValueDataTypeDescr_QNAME, String.class, DataValue.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fascicolo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "fascicolo", scope = GetCartellaWSResponse.class)
    public JAXBElement<Fascicolo> createGetCartellaWSResponseFascicolo(Fascicolo value) {
        return new JAXBElement<Fascicolo>(_GetCartellaWSResponseFascicolo_QNAME, Fascicolo.class, GetCartellaWSResponse.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "ragioneSociale", scope = Anagrafica.class)
    public JAXBElement<String> createAnagraficaRagioneSociale(String value) {
        return new JAXBElement<String>(_AnagraficaRagioneSociale_QNAME, String.class, Anagrafica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "cognome", scope = Anagrafica.class)
    public JAXBElement<String> createAnagraficaCognome(String value) {
        return new JAXBElement<String>(_AnagraficaCognome_QNAME, String.class, Anagrafica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "nome", scope = Anagrafica.class)
    public JAXBElement<String> createAnagraficaNome(String value) {
        return new JAXBElement<String>(_AnagraficaNome_QNAME, String.class, Anagrafica.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Fascicolo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dati.gestorefascicolows.equitalia.it", name = "fascicolo", scope = GetFascicoloWSResponse.class)
    public JAXBElement<Fascicolo> createGetFascicoloWSResponseFascicolo(Fascicolo value) {
        return new JAXBElement<Fascicolo>(_GetCartellaWSResponseFascicolo_QNAME, Fascicolo.class, GetFascicoloWSResponse.class, value);
    }

}
