//
// Generated By:JAX-WS RI IBM 2.0_03-07/07/2008 01:00 PM(foreman)-fcs (JAXB RI IBM 2.0.5-02/25/2009 05:47 AM(foreman)-fcs)
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dati.gestorefascicolows.equitalia.it", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package it.equitalia.gestorefascicolows.dati;
